# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pateint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('time_of_admission', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.CharField(max_length=30)),
                ('bed_type', models.CharField(max_length=10)),
                ('mode_of_arrival', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('injuries', models.CharField(max_length=50)),
                ('deposition', models.CharField(max_length=50)),
                ('time_of_surgery', models.CharField(max_length=20)),
                ('kin_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('time_of_death', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
