# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bed',
        ),
        migrations.AddField(
            model_name='patient',
            name='bed_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
