# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pateint',
            name='created_date',
        ),
        migrations.AddField(
            model_name='pateint',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pateint',
            name='deposition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pateint',
            name='injuries',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pateint',
            name='kin_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pateint',
            name='relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pateint',
            name='time_of_death',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pateint',
            name='time_of_surgery',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
