# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_count',
            field=models.CharField(max_length=25),
        ),
    ]
