# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contactId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=50)),
                ('question', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosppatients', to='eBedTrack.Hospital'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_count',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed_type',
            field=models.CharField(choices=[('1', 'ICU/CC'), ('2', 'EU'), ('3', 'MED/SURG'), ('4', 'OB'), ('5', 'SICU'), ('6', 'Neg-Pres/Iso'), ('7', 'OR'), ('8', 'Peds'), ('9', 'PICU'), ('10', 'NICU'), ('11', 'Burn'), ('12', 'Mental-Health'), ('13', 'Other')], default='ICU ', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=10),
        ),
    ]
