# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0002_auto_20171113_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
