# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0003_auto_20170930_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(choices=[('ICU', 'ICU'), ('ER', 'ER'), ('MED', 'MED')], max_length=50),
        ),
    ]
