# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0004_auto_20171113_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_count',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ph',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
