# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0002_auto_20171113_1928'),
        ('eBedTrack', '0004_auto_20171113_1451'),
    ]

    operations = [
    ]
