# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0005_auto_20171002_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_id',
            field=models.IntegerField(default=501, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nurse',
            name='nurse_id',
            field=models.AutoField(default=5001, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=6001, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='admin_id',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
