# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0006_auto_20171114_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
