# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0009_auto_20171024_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bed_id',
            field=models.CharField(max_length=20),
        ),
    ]
